using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Wordprocessing;

namespace CSSPWebToolsTaskRunner.Services
{

    // Enum Word
    public enum BulletStyleEnum
    {
        Error = 0,
        Bullet = 1,
        Number = 2,
        NumberAndLetter = 3,
    }
    public enum NumberingStyleEnum
    {
        Error = 0,
        NoList = 1,

    }
    public enum RunStyleEnum
    {
        Error = 0,
        Hyperlink = 1,
        Heading1Char = 2,
        Heading2Char = 3,
        Heading3Char = 4,
        Heading4Char = 5,
        Heading5Char = 6,
        TitleChar = 7,
        SubtitleChar = 8,
        SubtleEmphasis = 9,
        Emphasis = 10,
        IntenseEmphasis = 11,
        Strong = 12,
        QuoteChar = 13,
        IntenseQuoteChar = 14,
        BookTitle = 15,
        IntenseReference = 16,
        SubtleReference = 17,
        HeaderChar = 18,
        FooterChar = 19,
        DefaultParagraphFont = 20,
    }
    public enum ParagraphStyleEnum
    {
        Error = 0,
        Normal = 1,
        NoSpacing = 2,
        Heading1 = 3,
        Heading2 = 4,
        Heading3 = 5,
        Heading4 = 6,
        Heading5 = 7,
        Title = 8,
        Subtitle = 9,
        SubtleEmphasis = 10,
        Emphasis = 11,
        IntenseEmphasis = 12,
        Strong = 13,
        Quote = 14,
        IntenseQuote = 15,
        SubtleReference = 16,
        IntenseReference = 17,
        BookTitle = 18,
        ListParagraph = 19,
        NoList = 21,
        TOCHeading = 22,
        TOC1 = 23,
        TOC2 = 24,
        TOC3 = 25,
        Header = 26,
        Footer = 27,
        Caption = 28,
        TableofFigures = 29,

    }
    public enum TableStyleEnum
    {
        Error = 0,
        TableGrid = 1,
        TableNormal = 2,
        TableGridLight = 3,
        PlainTable1 = 4,
        PlainTable2 = 5,
        PlainTable3 = 6,
        PlainTable4 = 7,
        PlainTable5 = 8,
        GridTable1Light = 9,
        GridTable1Light_Accent1 = 10,
        GridTable1Light_Accent2 = 11,
        GridTable1Light_Accent3 = 12,
        GridTable1Light_Accent4 = 13,
        GridTable1Light_Accent5 = 14,
        GridTable1Light_Accent6 = 15,
        GridTable2 = 16,
        GridTable2_Accent1 = 17,
        GridTable2_Accent2 = 18,
        GridTable2_Accent3 = 19,
        GridTable2_Accent4 = 20,
        GridTable2_Accent5 = 21,
        GridTable2_Accent6 = 22,
        GridTable3 = 23,
        GridTable3_Accent1 = 24,
        GridTable3_Accent2 = 25,
        GridTable3_Accent3 = 26,
        GridTable3_Accent4 = 27,
        GridTable3_Accent5 = 28,
        GridTable3_Accent6 = 29,
        GridTable4 = 30,
        GridTable4_Accent1 = 31,
        GridTable4_Accent2 = 32,
        GridTable4_Accent3 = 33,
        GridTable4_Accent4 = 34,
        GridTable4_Accent5 = 35,
        GridTable4_Accent6 = 36,
        GridTable5Dark = 37,
        GridTable5Dark_Accent1 = 38,
        GridTable5Dark_Accent2 = 39,
        GridTable5Dark_Accent3 = 40,
        GridTable5Dark_Accent4 = 41,
        GridTable5Dark_Accent5 = 42,
        GridTable5Dark_Accent6 = 43,
        GridTable6Colorful = 44,
        GridTable6Colorful_Accent1 = 45,
        GridTable6Colorful_Accent2 = 46,
        GridTable6Colorful_Accent3 = 47,
        GridTable6Colorful_Accent4 = 48,
        GridTable6Colorful_Accent5 = 49,
        GridTable6Colorful_Accent6 = 50,
        GridTable7Colorful = 51,
        GridTable7Colorful_Accent1 = 52,
        GridTable7Colorful_Accent2 = 53,
        GridTable7Colorful_Accent3 = 54,
        GridTable7Colorful_Accent4 = 55,
        GridTable7Colorful_Accent5 = 56,
        GridTable7Colorful_Accent6 = 57,
        ListTable1Light = 58,
        ListTable1Light_Accent1 = 59,
        ListTable1Light_Accent2 = 60,
        ListTable1Light_Accent3 = 61,
        ListTable1Light_Accent4 = 62,
        ListTable1Light_Accent5 = 63,
        ListTable1Light_Accent6 = 64,
        ListTable2 = 65,
        ListTable2_Accent1 = 66,
        ListTable2_Accent2 = 67,
        ListTable2_Accent3 = 68,
        ListTable2_Accent4 = 69,
        ListTable2_Accent5 = 70,
        ListTable2_Accent6 = 71,
        ListTable3 = 72,
        ListTable3_Accent1 = 73,
        ListTable3_Accent2 = 74,
        ListTable3_Accent3 = 75,
        ListTable3_Accent4 = 76,
        ListTable3_Accent5 = 77,
        ListTable3_Accent6 = 78,
        ListTable4 = 79,
        ListTable4_Accent1 = 80,
        ListTable4_Accent2 = 81,
        ListTable4_Accent3 = 82,
        ListTable4_Accent4 = 83,
        ListTable4_Accent5 = 84,
        ListTable4_Accent6 = 85,
        ListTable5Dark = 86,
        ListTable5Dark_Accent1 = 87,
        ListTable5Dark_Accent2 = 88,
        ListTable5Dark_Accent3 = 89,
        ListTable5Dark_Accent4 = 90,
        ListTable5Dark_Accent5 = 91,
        ListTable5Dark_Accent6 = 92,
        ListTable6Colorful = 93,
        ListTable6Colorful_Accent1 = 94,
        ListTable6Colorful_Accent2 = 95,
        ListTable6Colorful_Accent3 = 96,
        ListTable6Colorful_Accent4 = 97,
        ListTable6Colorful_Accent5 = 98,
        ListTable6Colorful_Accent6 = 99,
        ListTable7Colorful = 100,
        ListTable7Colorful_Accent1 = 101,
        ListTable7Colorful_Accent2 = 102,
        ListTable7Colorful_Accent3 = 103,
        ListTable7Colorful_Accent4 = 104,
        ListTable7Colorful_Accent5 = 105,
        ListTable7Colorful_Accent6 = 106,

    }
}
