//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSSPWebToolsTaskRunner.Services.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DocxServiceSubsectorFCDensitiesRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DocxServiceSubsectorFCDensitiesRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSSPWebToolsTaskRunner.Services.Resources.DocxServiceSubsectorFCDensitiesRes", typeof(DocxServiceSubsectorFCDensitiesRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0-24h.
        /// </summary>
        public static string _0_24h {
            get {
                return ResourceManager.GetString("_0_24h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0-48h.
        /// </summary>
        public static string _0_48h {
            get {
                return ResourceManager.GetString("_0_48h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0-72h.
        /// </summary>
        public static string _0_72h {
            get {
                return ResourceManager.GetString("_0_72h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find tide site.
        /// </summary>
        public static string CoundNotFindTideSite {
            get {
                return ResourceManager.GetString("CoundNotFindTideSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feacal Coliform Densities (MPN/100mL).
        /// </summary>
        public static string FaecalColiformDensitiesMPNPer100 {
            get {
                return ResourceManager.GetString("FaecalColiformDensitiesMPNPer100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for.
        /// </summary>
        public static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain (mm).
        /// </summary>
        public static string Rain_mm {
            get {
                return ResourceManager.GetString("Rain_mm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station.
        /// </summary>
        public static string Station {
            get {
                return ResourceManager.GetString("Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tide.
        /// </summary>
        public static string Tide {
            get {
                return ResourceManager.GetString("Tide", resourceCulture);
            }
        }
    }
}
