//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSSPWebToolsTaskRunner.Services.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DocxServiceSubsectorFCSummaryStatRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DocxServiceSubsectorFCSummaryStatRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSSPWebToolsTaskRunner.Services.Resources.DocxServiceSubsectorFCSummaryStatRes", typeof(DocxServiceSubsectorFCSummaryStatRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for.
        /// </summary>
        public static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometric Mean &gt; 14.
        /// </summary>
        public static string GeometricMeanBigger14 {
            get {
                return ResourceManager.GetString("GeometricMeanBigger14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G Mean.
        /// </summary>
        public static string GMean {
            get {
                return ResourceManager.GetString("GMean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max FC.
        /// </summary>
        public static string MaxFC {
            get {
                return ResourceManager.GetString("MaxFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Median.
        /// </summary>
        public static string Median {
            get {
                return ResourceManager.GetString("Median", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Median &gt; 14.
        /// </summary>
        public static string MedianBigger14 {
            get {
                return ResourceManager.GetString("MedianBigger14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min FC.
        /// </summary>
        public static string MinFC {
            get {
                return ResourceManager.GetString("MinFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P90.
        /// </summary>
        public static string P90 {
            get {
                return ResourceManager.GetString("P90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 90th Percentile &gt; 43.
        /// </summary>
        public static string Perc90Bigger43 {
            get {
                return ResourceManager.GetString("Perc90Bigger43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % &gt; 43.
        /// </summary>
        public static string PercBigger43 {
            get {
                return ResourceManager.GetString("PercBigger43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (% &gt; 43) &gt; 10.
        /// </summary>
        public static string PercBigger43More10Perc {
            get {
                return ResourceManager.GetString("PercBigger43More10Perc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        public static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samples.
        /// </summary>
        public static string Samples {
            get {
                return ResourceManager.GetString("Samples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station.
        /// </summary>
        public static string Station {
            get {
                return ResourceManager.GetString("Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary statistics of faecal coliform densities (MPN/100ml).
        /// </summary>
        public static string SummaryStatOfFCDensitiesMPNPer100 {
            get {
                return ResourceManager.GetString("SummaryStatOfFCDensitiesMPNPer100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following values have been shaded.
        /// </summary>
        public static string TheFollowingValuesHaveBeenShaded {
            get {
                return ResourceManager.GetString("TheFollowingValuesHaveBeenShaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subsector FC Summary Stat.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
